name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Prepare
      run: sudo apt-get update && sudo apt-get install ocl-icd-opencl-dev libhwloc-dev

    - name: Build ffi
      run: git submodule update --init --recursive && make ffi
      
    - name: Build
      run: make

    - name: Test
      run: go test -v ./...
